using MeetIQ.Application.Features.Notes.DTOs;
using MeetIQ.Domain.Entities;

namespace MeetIQ.Application.Interfaces.Repositories
{
    public interface INoteRepository : IRepository<Note>
    {
        Task<Note> GetWithNoteTagsAsync(Guid id);
        Task<NoteDetailsDto?> GetByIdAsync(Guid id);
        Task<(IEnumerable<NoteCardDto> Items, int Total)> GetNotesAsync(
            string userId,
            string? search,
            string? tag,
            bool? isAutoGenerated,
            int page,
            int pageSize);
    }
}