using MediatR;
using MeetIQ.Application.Common.Results;
using MeetIQ.Application.Interfaces.Repositories;

namespace MeetIQ.Application.Features.Notes.Queries.GetNotesQuery
{
    public class GetNotesQueryHandler : IRequestHandler<GetNotesQuery, NotesIndexResult>
    {
        private readonly INoteRepository _noteRepository;
        private readonly ITagRepository _tagRepository;

        public GetNotesQueryHandler(INoteRepository noteRepository, ITagRepository tagRepository)
        {
            _noteRepository = noteRepository;
            _tagRepository = tagRepository;
        }

        public async Task<NotesIndexResult> Handle(GetNotesQuery request, CancellationToken cancellationToken)
        {
            bool? isAutoGenerated = request.Filter switch
            {
                "ai" => true,
                "manual" => false,
                _ => null
            };

            var (notes, total) = await _noteRepository.GetNotesAsync(
                userId: request.UserId,
                search: request.Search,
                tag: request.Tag,
                isAutoGenerated: isAutoGenerated,
                page: request.Page,
                pageSize: request.PageSize);

            var allTags = await _tagRepository.GetAllNamesAsync();

            return new NotesIndexResult
            {
                Notes = notes,
                Total = total,
                AllTags = allTags
            };
        }
    }
}