using MediatR;
using MeetIQ.Application.Interfaces.Repositories;
using MeetIQ.Application.Interfaces.Services;
using MeetIQ.Domain.Entities;
using Microsoft.Extensions.Logging;
using MeetIQ.Domain.Enums;
using System.Text.Json;

namespace MeetIQ.Application.Features.Meetings.Commands.AnalyzeMeetingCommand
{
    public class AnalyzeMeetingCommandHandler
        : IRequestHandler<AnalyzeMeetingCommand, AnalyzeMeetingResult>
    {
        private readonly ISummaryRepository meetingSummaryRepository;
        private readonly IAnalysisService analysisService;
        private readonly IMeetingRepository meetingRepository;
        private readonly ITaskRepository taskRepository;
        private readonly INoteRepository noteRepository;
        private readonly ILogger<AnalyzeMeetingCommandHandler> _logger;

        public AnalyzeMeetingCommandHandler(
            ISummaryRepository meetingSummaryRepository,
            IAnalysisService analysisService,
            IMeetingRepository meetingRepository,
            ITaskRepository taskRepository,
            INoteRepository noteRepository,
            ILogger<AnalyzeMeetingCommandHandler> logger)
        {
            this.meetingSummaryRepository = meetingSummaryRepository;
            this.analysisService = analysisService;
            this.meetingRepository = meetingRepository;
            this.taskRepository = taskRepository;
            this.noteRepository = noteRepository;
            _logger = logger;
        }

        public async Task<AnalyzeMeetingResult> Handle(
            AnalyzeMeetingCommand request,
            CancellationToken ct)
        {
            // 1. Load meeting + transcript
            var meeting = await meetingRepository.GetMeetingWithTranscription(request.MeetingId, ct);

            if (meeting is null)
                return new(false, "Meeting not found.");

            if (meeting.HostId != request.RequestedByUserId)
                return new(false, "Only the host can generate analysis.");

            var transcript = meeting.Transcript;
            if (transcript is null || string.IsNullOrWhiteSpace(transcript.Text))
                return new(false, "Transcript text not available. Please transcribe first.");

            try
            {
                // 2. Call Gemini
                _logger.LogInformation("Sending transcript to Gemini for meeting {Id}", meeting.Id);
                var analysis = await analysisService.AnalyzeTranscriptAsync(
                    transcript.Text,
                    meeting.Title,
                    ct);

                // 3. Save / update Summary
                var existingSummary = await meetingSummaryRepository.GetAsync(s => s.MeetingId == meeting.Id);

                // KeyDecisions serialized as JSON array string
                var keyDecisionsJson = analysis.KeyDecisions.Any()
                    ? JsonSerializer.Serialize(analysis.KeyDecisions)
                    : null;

                if (existingSummary is null)
                {
                    await meetingSummaryRepository.AddAsync(new MeetingSummary
                    {
                        MeetingId = meeting.Id,
                        SummaryText = analysis.Summary,
                        KeyInsights = analysis.KeyInsights,
                        KeyDecisions = keyDecisionsJson,
                        GeneratedAt = DateTime.UtcNow,
                    });
                }
                else
                {
                    existingSummary.SummaryText = analysis.Summary;
                    existingSummary.KeyInsights = analysis.KeyInsights;
                    existingSummary.KeyDecisions = keyDecisionsJson;
                    existingSummary.UpdatedAt = DateTime.UtcNow;
                    existingSummary.IsEdited = false;
                }

                // 4. Save Tasks
                foreach (var t in analysis.Tasks)
                {
                    var priority = t.Priority?.ToLower() switch
                    {
                        "high" => TaskPriority.High,
                        "medium" => TaskPriority.Medium,
                        _ => TaskPriority.Low
                    };

                    DateTime? dueDate = null;
                    if (t.DueDate is not null &&
                        DateTime.TryParse(t.DueDate, out var parsed))
                        dueDate = DateTime.SpecifyKind(parsed, DateTimeKind.Utc);

                    await taskRepository.AddAsync(new TaskItem
                    {
                        Title = t.Title,
                        Description = t.Description,
                        Priority = priority,
                        DueDate = dueDate,
                        MeetingId = meeting.Id,
                        UserId = request.RequestedByUserId,
                        IsAutoGenerated = true,
                        Status = Domain.Enums.TaskStatus.ToDo,
                        CreatedAt = DateTime.UtcNow,
                    });
                }

                // 5. Save Notes
                foreach (var n in analysis.Notes)
                {
                    await noteRepository.AddAsync(new Note
                    {
                        Title = n.Title,
                        Content = n.Content,
                        MeetingId = meeting.Id,
                        AuthorId = request.RequestedByUserId,
                        IsAutoGenerated = true,
                        CreatedAt = DateTime.UtcNow,
                    });
                }

                await taskRepository.SaveChangesAsync();

                _logger.LogInformation(
                    "Analysis saved for meeting {Id}: {Tasks} tasks, {Notes} notes",
                    meeting.Id, analysis.Tasks.Count, analysis.Notes.Count);

                return new(true, null);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Analysis failed for meeting {Id}", meeting.Id);
                return new(false, ex.Message);
            }
        }
    }
}