using MeetIQ.Application.Interfaces;

namespace MeetIQ.Application.Features.Notes.Commands.CreateNoteCommand
{
    public class CreateNoteCommand : ICommand<Guid>
    {
        public string Title { get; set; }
        public string Content { get; set; }
        public string AuthorId { get; set; }
        public Guid? MeetingId { get; set; }
        public Guid? CalendarEventId { get; set; }
        public List<string> Tags { get; set; } = new();
        public bool IsAutoGenerated { get; set; } = false;
    }
}