using MediatR;
using MeetIQ.Application.Common.Exceptions;
using MeetIQ.Application.Interfaces.Repositories;
using MeetIQ.Domain.Entities;



namespace MeetIQ.Application.Features.Notes.Commands.CreateNoteCommand
{
    public class CreateNoteCommandHandler : IRequestHandler<CreateNoteCommand, Guid>
    {
        private readonly INoteRepository _noteRepository;
        private readonly ITagRepository _tagRepository;
        private readonly IMeetingRepository _meetingRepository;

        public CreateNoteCommandHandler(
            INoteRepository noteRepository,
            ITagRepository tagRepository,
            IMeetingRepository meetingRepository)
        {
            _noteRepository = noteRepository;
            _tagRepository = tagRepository;
            _meetingRepository = meetingRepository;
        }

        public async Task<Guid> Handle(CreateNoteCommand request, CancellationToken cancellationToken)
        {
            if (request.MeetingId.HasValue)
            {
                var meeting = await _meetingRepository.GetAsync(x => x.Id == request.MeetingId);
                if (meeting == null)
                    throw new NotFoundException("Meeting not found");
            }

            var note = new Note
            {
                Id = Guid.NewGuid(),
                Title = request.Title,
                Content = request.Content,
                AuthorId = request.AuthorId,
                MeetingId = request.MeetingId,
                CalendarEventId = request.CalendarEventId,
                IsAutoGenerated = request.IsAutoGenerated,
                IsEdited = false,
                CreatedAt = DateTime.UtcNow,
                UpdatedAt = DateTime.UtcNow
            };

            // Handle tags
            if (request.Tags.Any())
            {
                foreach (var tagName in request.Tags.Distinct())
                {
                    var tag = await _tagRepository.GetOrCreateAsync(tagName.Trim().ToLower());
                    note.NoteTags.Add(new NoteTag { NoteId = note.Id, TagId = tag.Id });
                }
            }

            await _noteRepository.AddAsync(note);
            await _noteRepository.SaveChangesAsync();

            return note.Id;
        }
    }
}