using Dapper;
using MeetIQ.Application.Features.Dashboard.DTOs;
using MeetIQ.Application.Interfaces.Repositories;
using MeetIQ.Infrastructure.Persistence.Repositories;
using SqlKata.Execution;

namespace MeetIQ.Infrastructure.Persistence.Repositories
{
    public class DashboardRepository : IDashboardRepository
    {
        private readonly QueryFactory db;

        public DashboardRepository(QueryFactory db)
        {
            this.db = db;
        }

        public async Task<DashboardStatsDto> GetStatsAsync(string userId)
        {
            var now = DateTime.UtcNow;

            var totalMeetings = await db.Query("Meetings")
                .Where("HostId", userId)
                //.Where("IsDeleted", false)
                .CountAsync<int>();

            var upcomingCount = await db.Query("Meetings as m")
                .LeftJoin("MeetingParticipants as mp", "mp.MeetingId", "m.Id")
                .Where(q => q
                    .Where("m.HostId", userId)
                    .OrWhere("mp.UserId", userId))
                .Where("m.ScheduledAt", ">", now)
                //.Where("m.IsDeleted", false)
                .CountAsync<int>();

            var pendingTasks = await db.Query("TaskItems")
                .Where("UserId", userId)
                .Where("Status", 0) // ToDo
                .Where("IsDeleted", false)
                .CountAsync<int>();

            var totalNotes = await db.Query("Notes")
                .Where("AuthorId", userId)
                .Where("IsDeleted", false)
                .CountAsync<int>();

            var unprocessedTranscripts = await db.Query("MeetingTranscripts as t")
                .Join("Meetings as m", "m.Id", "t.MeetingId")
                .Where("m.HostId", userId)
                .Where("t.IsProcessed", false)
                .CountAsync<int>();

            return new DashboardStatsDto
            {
                TotalMeetingsHosted = totalMeetings,
                UpcomingMeetingsCount = upcomingCount,
                PendingTasksCount = pendingTasks,
                TotalNotesCount = totalNotes,
                UnprocessedTranscriptsCount = unprocessedTranscripts
            };
        }


        public async Task<List<UpcomingMeetingDto>> GetUpcomingMeetingsAsync(string userId, int count = 5)
        {
            var now = DateTime.UtcNow;

            var sql = """
                SELECT DISTINCT
                    m.Id,
                    m.Title,
                    m.ScheduledAt,
                    m.Status,
                    m.JitsiRoomId,
                    (SELECT COUNT(*) FROM MeetingParticipants WHERE MeetingId = m.Id) AS ParticipantsCount,
                    CASE WHEN m.HostId = @UserId THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END AS IsHost
                FROM Meetings m
                LEFT JOIN MeetingParticipants mp ON mp.MeetingId = m.Id
                WHERE (m.HostId = @UserId OR mp.UserId = @UserId)
                  AND m.ScheduledAt > @Now
                  --AND m.IsDeleted = 0
                ORDER BY m.ScheduledAt
                OFFSET 0 ROWS FETCH NEXT @Count ROWS ONLY
                """;

            var connection = db.Connection; 

            var items = await connection.QueryAsync<UpcomingMeetingDto>(sql, new
            {
                UserId = userId,
                Now = now,
                Count = count
            });

            return items.ToList();
        }

        public async Task<List<RecentTaskDto>> GetRecentTasksAsync(string userId, int count = 5)
        {
            var items = await db.Query("TaskItems as t")
                .Select(
                    "t.Id",
                    "t.Title",
                    "t.Priority",
                    "t.Status",
                    "t.DueDate",
                    "t.IsAutoGenerated",
                    "m.Title as MeetingTitle"
                )
                .LeftJoin("Meetings as m", "m.Id", "t.MeetingId")
                .Where("t.UserId", userId)
                .Where("t.IsDeleted", false)
                .OrderByDesc("t.CreatedAt")
                .Limit(count)
                .GetAsync<RecentTaskDto>();

            return items.ToList();
        }

        public async Task<List<RecentNoteDto>> GetRecentNotesAsync(string userId, int count = 5)
        {
            var items = await db.Query("Notes as n")
                .Select(
                    "n.Id",
                    "n.Title",
                    "n.Content",
                    "n.IsAutoGenerated",
                    "n.CreatedAt",
                    "m.Title as MeetingTitle"
                )
                .LeftJoin("Meetings as m", "m.Id", "n.MeetingId")
                .Where("n.AuthorId", userId)
                .Where("n.IsDeleted", false)
                .OrderByDesc("n.CreatedAt")
                .Limit(count)
                .GetAsync<RecentNoteDto>();

            return items.ToList();
        }
    }
}