using MeetIQ.Application.Features.Notes.DTOs;
using MeetIQ.Application.Interfaces.Repositories;
using MeetIQ.Domain.Entities;
using MeetIQ.Infrastructure.Presistence.Repositories;
using MeetIQ.Infrastructure.Presistence;
using SqlKata.Execution;
using Microsoft.EntityFrameworkCore;

namespace MeetIQ.Infrastructure.Persistence.Repositories
{
    public class NoteRepository : Repository<Note>, INoteRepository
    {
        public NoteRepository(ApplicationDbContext context, QueryFactory db)
            : base(context, db) { }


        public async Task<Note> GetWithNoteTagsAsync(Guid id)
        {
            return await context.Notes
                 .Include(n => n.NoteTags)
                 .FirstOrDefaultAsync(n => n.Id == id);
        }

        public async Task<NoteDetailsDto?> GetByIdAsync(Guid id)
        {
            var note = await db.Query("Notes as n")
                .Select(
                    "n.Id", "n.Title", "n.Content",
                    "n.IsAutoGenerated", "n.IsEdited",
                    "n.CreatedAt", "n.UpdatedAt",
                    "n.AuthorId",
                    "u.FullName as AuthorName",
                    "n.MeetingId", "m.Title  as MeetingTitle",
                    "n.CalendarEventId", "ce.Title as CalendarEventTitle"
                )
                .Join("AspNetUsers as u", "u.Id", "n.AuthorId")
                .LeftJoin("Meetings as m", "m.Id", "n.MeetingId")
                .LeftJoin("CalendarEvents as ce", "ce.Id", "n.CalendarEventId")
                .Where("n.Id", id)
                .Where("n.IsDeleted", false)
                .FirstOrDefaultAsync<NoteDetailsDto>();

            if (note is null) return null;

            note.Tags = (await db.Query("NoteTags as nt")
                .Select("t.Id", "t.Name")
                .Join("Tags as t", "t.Id", "nt.TagId")
                .Where("nt.NoteId", id)
                .GetAsync<TagDto>()).ToList();

            return note;
        }

        public async Task<(IEnumerable<NoteCardDto> Items, int Total)> GetNotesAsync(
            string userId,
            string? search,
            string? tag,
            bool? isAutoGenerated,
            int page,
            int pageSize)
        {
            var baseQuery = db.Query("Notes as n")
                .Select(
                    "n.Id", "n.Title",
                    "n.IsAutoGenerated", "n.IsEdited",
                    "n.CreatedAt", "n.UpdatedAt",
                    "u.FullName  as AuthorName",
                    "m.Title     as MeetingTitle",
                    "ce.Title    as CalendarEventTitle"
                )
                .Join("AspNetUsers as u", "u.Id", "n.AuthorId")
                .LeftJoin("Meetings as m", "m.Id", "n.MeetingId")
                .LeftJoin("CalendarEvents as ce", "ce.Id", "n.CalendarEventId")
                .Where("n.AuthorId", userId)
                .Where("n.IsDeleted", false);

            if (!string.IsNullOrWhiteSpace(search))
                baseQuery.WhereLike("n.Title", $"%{search}%");

            if (!string.IsNullOrWhiteSpace(tag))
                baseQuery.WhereIn("n.Id", q =>
                    q.From("NoteTags as nt")
                     .Select("nt.NoteId")
                     .Join("Tags as t", "t.Id", "nt.TagId")
                     .WhereRaw("LOWER(t.Name) = LOWER(?)", tag));

            if (isAutoGenerated.HasValue)
                baseQuery.Where("n.IsAutoGenerated", isAutoGenerated.Value);

            var total = await baseQuery.Clone().CountAsync<int>();

            var rows = await baseQuery
                .OrderByDesc("n.UpdatedAt")
                .ForPage(page, pageSize)
                .GetAsync<NoteCardDto>();

            var items = rows.ToList();

            // Hydrate ContentSnippet (strip HTML, truncate) 
            if (items.Count > 0)
            {
                var ids = items.Select(x => x.Id).ToList();

                var contents = await db.Query("Notes")
                    .Select("Id", "Content")
                    .WhereIn("Id", ids)
                    .GetAsync<dynamic>();

                var contentMap = contents.ToDictionary(
                    (dynamic x) => (Guid)x.Id,
                    (dynamic x) =>
                    {
                        string html = (string)(x.Content ?? "");
                        string plain = StripHtml(html);
                        return plain.Length > 150 ? plain[..150].TrimEnd() + "…" : plain;
                    });

                // Hydrate Tags 
                var tagRows = await db.Query("NoteTags as nt")
                    .Select("nt.NoteId", "t.Name")
                    .Join("Tags as t", "t.Id", "nt.TagId")
                    .WhereIn("nt.NoteId", ids)
                    .GetAsync<dynamic>();

                var tagMap = tagRows
                    .GroupBy((dynamic x) => (Guid)x.NoteId)
                    .ToDictionary(
                        g => g.Key,
                        g => (IEnumerable<string>)g.Select((dynamic x) => (string)x.Name).ToList());

                foreach (var item in items)
                {
                    item.ContentSnippet = contentMap.GetValueOrDefault(item.Id, "");
                    item.Tags = tagMap.GetValueOrDefault(item.Id, []);
                }
            }

            return (items, total);
        }

        // Tiny HTML stripper (no regex dependency) 
        private static string StripHtml(string html)
        {
            if (string.IsNullOrEmpty(html)) return "";
            var sb = new System.Text.StringBuilder();
            bool inTag = false;
            foreach (char c in html)
            {
                if (c == '<') { inTag = true; continue; }
                if (c == '>') { inTag = false; continue; }
                if (!inTag) sb.Append(c);
            }
            return sb.ToString().Trim();
        }
    }
}