////using MeetIQ.Application.Common.Options;
////using MeetIQ.Application.Interfaces.Repositories;
////using MeetIQ.Domain.Entities;
////using SqlKata.Execution;

////namespace MeetIQ.Infrastructure.Presistence.Repositories
////{
////    public class NoteRepository : Repository<Note>, INoteRepository
////    {
////        public NoteRepository(ApplicationDbContext context, QueryFactory db) : base(context, db)
////        {
////        }


////        public async Task<IEnumerable<SelectOption>> GetMeetingsAsync()
////        {
////            var data = await db.Query("Meetings")
////                .Select("Id", "Title")
////                .OrderByDesc("ScheduledAt")
////                .GetAsync();

////            return data.Select(x => new SelectOption(x.Id.ToString(), x.Title));
////        }

////        public async Task<IEnumerable<SelectOption>> GetCalendarEventsAsync()
////        {
////            var data = await db.Query("CalendarEvents")
////                .Select("Id", "Title")
////                .OrderByDesc("StartTime")
////                .GetAsync();

////            return data.Select(x => new SelectOption(x.Id.ToString(), x.Title));
////        }

////        public async Task<IEnumerable<string>> GetAllTagsAsync()
////        {
////            return await db.Query("Tags")
////                .Select("Name")
////                .OrderBy("Name")
////                .GetAsync<string>();
////        }
////    }
////}




//using System.Text.RegularExpressions;
//using MeetIQ.Application.Common.Results;
//using MeetIQ.Application.Features.Notes.DTOs;
//using MeetIQ.Domain.Entities;
//using SqlKata.Execution;
//using Microsoft.EntityFrameworkCore;
//using MeetIQ.Application.Interfaces.Repositories;
//using MeetIQ.Application.Features.Notes.Queries.GetNotes;

//namespace MeetIQ.Infrastructure.Presistence.Repositories
//{
//    public class NoteRepository : Repository<Note>, INoteRepository
//    {
//        // db  = SqlKata QueryFactory  (injected via base)
//        // context = EF Core DbContext (injected via base)

//        public NoteRepository(ApplicationDbContext context, QueryFactory db)
//            : base(context, db) { }

//        // ══════════════════════════════════════════════════════════════════════
//        //  READ — SqlKata queries (no EF tracking)
//        // ══════════════════════════════════════════════════════════════════════

//        public async Task<PagedResult<NoteListItemDto>> GetNotesAsync(GetAllNotesQuery query)
//        {
//            // ── Base query ────────────────────────────────────────────────────
//            var baseQuery = db.Query("Notes as n")
//                .Join("AspNetUsers as u", "u.Id", "n.AuthorId")
//                .LeftJoin("Meetings as m", "m.Id", "n.MeetingId")
//                .LeftJoin("CalendarEvents as ce", "ce.Id", "n.CalendarEventId")
//                .Where("n.AuthorId", query.UserId)
//                .Where("n.IsDeleted", false);

//            // ── Filters ───────────────────────────────────────────────────────
//            if (!string.IsNullOrWhiteSpace(query.Search))
//                baseQuery.WhereRaw(
//                    "(n.Title LIKE ? OR n.Content LIKE ?)",
//                    $"%{query.Search}%", $"%{query.Search}%");

//            if (!string.IsNullOrWhiteSpace(query.Tag))
//                baseQuery.WhereExists(q =>
//                    q.From("NoteTags as nt")
//                     .Join("Tags as t", "t.Id", "nt.TagId")
//                     .WhereRaw("nt.NoteId = n.Id")
//                     .Where("t.Name", query.Tag));

//            if (query.FilterType == "ai")
//                baseQuery.Where("n.IsAutoGenerated", true);
//            else if (query.FilterType == "manual")
//                baseQuery.Where("n.IsAutoGenerated", false);

//            // ── Count ─────────────────────────────────────────────────────────
//            var total = await baseQuery.Clone().CountAsync<int>();

//            // ── Page + select ─────────────────────────────────────────────────
//            var rows = await baseQuery
//                .Select(
//                    "n.Id",
//                    "n.Title",
//                    "n.Content        as ContentRaw",
//                    "n.IsAutoGenerated",
//                    "n.IsEdited",
//                    "n.CreatedAt",
//                    "n.UpdatedAt",
//                    "u.FullName        as AuthorName",
//                    "m.Title           as MeetingTitle",
//                    "ce.Title          as CalendarEventTitle"
//                )
//                .OrderByDesc("n.UpdatedAt")
//                .ForPage(query.Page, query.PageSize)
//                .GetAsync<NoteListRawRow>();

//            // ── Hydrate tags per note ─────────────────────────────────────────
//            var noteIds = rows.Select(r => r.Id).ToList();
//            var tagMap = await GetTagMapAsync(noteIds);

//            var items = rows.Select(r => new NoteListItemDto
//            {
//                Id = r.Id,
//                Title = r.Title,
//                ContentSnippet = Truncate(StripHtml(r.ContentRaw), 140),
//                IsAutoGenerated = r.IsAutoGenerated,
//                IsEdited = r.IsEdited,
//                CreatedAt = r.CreatedAt,
//                UpdatedAt = r.UpdatedAt,
//                AuthorName = r.AuthorName,
//                MeetingTitle = r.MeetingTitle,
//                CalendarEventTitle = r.CalendarEventTitle,
//                Tags = tagMap.TryGetValue(r.Id, out var t) ? t : []
//            }).ToList();

//            return new PagedResult<NoteListItemDto>
//            {
//                Items = items,
//                TotalCount = total,
//                Page = query.Page,
//                PageSize = query.PageSize
//            };
//        }

//        public async Task<NoteDetailsDto?> GetByIdAsync(Guid id, string userId)
//        {
//            var row = await db.Query("Notes as n")
//                .Join("AspNetUsers as u", "u.Id", "n.AuthorId")
//                .LeftJoin("Meetings as m", "m.Id", "n.MeetingId")
//                .LeftJoin("CalendarEvents as ce", "ce.Id", "n.CalendarEventId")
//                .Where("n.Id", id)
//                .Where("n.AuthorId", userId)
//                .Where("n.IsDeleted", false)
//                .Select(
//                    "n.Id",
//                    "n.Title",
//                    "n.Content",
//                    "n.IsAutoGenerated",
//                    "n.IsEdited",
//                    "n.CreatedAt",
//                    "n.UpdatedAt",
//                    "n.AuthorId",
//                    "u.FullName        as AuthorName",
//                    "n.MeetingId",
//                    "m.Title           as MeetingTitle",
//                    "n.CalendarEventId",
//                    "ce.Title          as CalendarEventTitle"
//                )
//                .FirstOrDefaultAsync<NoteDetailsDto>();

//            if (row is null) return null;

//            row.Tags = (await GetTagMapAsync([row.Id]))
//                       .TryGetValue(row.Id, out var tags) ? tags : [];

//            return row;
//        }

//        public async Task<List<string>> GetUserTagsAsync(string userId)
//        {
//            return (await db.Query("Tags as t")
//                .Join("NoteTags as nt", "nt.TagId", "t.Id")
//                .Join("Notes as n", "n.Id", "nt.NoteId")
//                .Where("n.AuthorId", userId)
//                .Where("n.IsDeleted", false)
//                .Select("t.Name")
//                .Distinct()
//                .OrderBy("t.Name")
//                .GetAsync<string>())
//                .ToList();
//        }

//        public async Task<List<MeetingSelectDto>> GetMeetingSelectListAsync()
//        {
//            return (await db.Query("Meetings")
//                //.Where("IsDeleted", false)
//                .Select("Id", "Title")
//                .OrderByDesc("ScheduledAt")
//                .GetAsync<MeetingSelectDto>())
//                .ToList();
//        }

//        public async Task<List<CalendarEventSelectDto>> GetCalendarEventSelectListAsync()
//        {
//            return (await db.Query("CalendarEvents")
//               // .Where("IsDeleted", false)
//                .Select("Id", "Title")
//                .OrderByDesc("StartTime")
//                .GetAsync<CalendarEventSelectDto>())
//                .ToList();
//        }

//        // ── Tag lookup used by both list and detail ───────────────────────────
//        private async Task<Dictionary<Guid, List<string>>> GetTagMapAsync(IEnumerable<Guid> noteIds)
//        {
//            var idList = noteIds.ToList();
//            if (!idList.Any()) return [];

//            var rows = await db.Query("NoteTags as nt")
//                .Join("Tags as t", "t.Id", "nt.TagId")
//                .WhereIn("nt.NoteId", idList)
//                .Select("nt.NoteId", "t.Name as TagName")
//                .GetAsync<NoteTagRawRow>();

//            return rows
//                .GroupBy(r => r.NoteId)
//                .ToDictionary(
//                    g => g.Key,
//                    g => g.Select(r => r.TagName).ToList());
//        }

//        // ══════════════════════════════════════════════════════════════════════
//        //  WRITE HELPERS — EF Core (used by command handlers via interface)
//        // ══════════════════════════════════════════════════════════════════════

//        /// <inheritdoc/>
//        public async Task<Tag?> GetTagByNameAsync(string name)
//        {
//            return await context.Tags
//                .FirstOrDefaultAsync(t => t.Name == name);
//        }

//        // ══════════════════════════════════════════════════════════════════════
//        //  Private helpers
//        // ══════════════════════════════════════════════════════════════════════

//        private static string StripHtml(string html) =>
//            string.IsNullOrWhiteSpace(html)
//                ? string.Empty
//                : Regex.Replace(html, "<.*?>", " ").Trim();

//        private static string Truncate(string s, int max) =>
//            s.Length <= max ? s : s[..max].TrimEnd() + "…";

//        // ── Internal projection rows ──────────────────────────────────────────
//        private sealed class NoteListRawRow
//        {
//            public Guid Id { get; set; }
//            public string Title { get; set; } = string.Empty;
//            public string ContentRaw { get; set; } = string.Empty;
//            public bool IsAutoGenerated { get; set; }
//            public bool IsEdited { get; set; }
//            public DateTime CreatedAt { get; set; }
//            public DateTime UpdatedAt { get; set; }
//            public string AuthorName { get; set; } = string.Empty;
//            public string? MeetingTitle { get; set; }
//            public string? CalendarEventTitle { get; set; }
//        }

//        private sealed class NoteTagRawRow
//        {
//            public Guid NoteId { get; set; }
//            public string TagName { get; set; } = string.Empty;
//        }
//    }
//}