using MeetIQ.Application.Features.SystemHealth.DTOs;
using MeetIQ.Application.Interfaces.Repositories;
using MeetIQ.Domain.Enums;
using SqlKata.Execution;

namespace MeetIQ.Infrastructure.Persistence.Repositories
{
    public class SystemHealthRepository : ISystemHealthRepository
    {
        private readonly QueryFactory db;

        public SystemHealthRepository(QueryFactory db)
        {
            this.db = db;
        }

        public async Task<SystemHealthDto> GetSystemHealthAsync()
        {
            var now = DateTime.UtcNow;
            var startOfMonth = new DateTime(now.Year, now.Month, 1);

            var totalUsers = await db.Query("AspNetUsers").CountAsync<int>();
            var activeUsers = await db.Query("AspNetUsers").Where("IsActive", true).CountAsync<int>();
            var newUsersThisMonth = await db.Query("AspNetUsers").Where("CreatedAt", ">=", startOfMonth).CountAsync<int>();

            var totalMeetings = await db.Query("Meetings").CountAsync<int>();
            var meetingsThisMonth = await db.Query("Meetings").Where("ScheduledAt", ">=", startOfMonth).CountAsync<int>();
            var liveMeetings = await db.Query("Meetings").Where("Status", (int)MeetingStatus.InProgress).CountAsync<int>();

            var totalTasks = await db.Query("TaskItems").Where("IsDeleted", false).CountAsync<int>();
            var pendingTasks = await db.Query("TaskItems").Where("IsDeleted", false).Where("Status", (int)Domain.Enums.TaskStatus.ToDo).CountAsync<int>();
            var completedTasks = await db.Query("TaskItems").Where("IsDeleted", false).Where("Status", (int)Domain.Enums.TaskStatus.Done).CountAsync<int>();

            var totalTranscripts = await db.Query("MeetingTranscripts").CountAsync<int>();
            var unprocessed = await db.Query("MeetingTranscripts").Where("IsProcessed", false).CountAsync<int>();
            var totalSummaries = await db.Query("MeetingSummaries").CountAsync<int>();
            var editedSummaries = await db.Query("MeetingSummaries").Where("IsEdited", true).CountAsync<int>();

            var totalNotes = await db.Query("Notes").CountAsync<int>();
            var aiNotes = await db.Query("Notes").Where("IsAutoGenerated", true).CountAsync<int>();

            var totalFeedback = await db.Query("FeedbackReports").CountAsync<int>();
            var openFeedback = await db.Query("FeedbackReports").Where("Status", (int)FeedbackStatus.Open).CountAsync<int>();
            var inReviewFeedback = await db.Query("FeedbackReports").Where("Status", (int)FeedbackStatus.InReview).CountAsync<int>();
            var bugReports = await db.Query("FeedbackReports").Where("Type", (int)FeedbackType.Bug).CountAsync<int>();


            // User growth (last 6 months) 
            var userGrowthRaw = await db.Query("AspNetUsers")
                .SelectRaw("FORMAT(CreatedAt, 'MMM') as Month, COUNT(*) as Count")
                .Where("CreatedAt", ">=", now.AddMonths(-5).Date)
                .GroupByRaw("FORMAT(CreatedAt, 'MMM'), MONTH(CreatedAt)")
                .OrderByRaw("MONTH(CreatedAt)")
                .GetAsync<UserGrowthPointDto>();

            // Meeting activity (last 6 months) 
            var meetingActivityRaw = await db.Query("Meetings")
                .SelectRaw("FORMAT(ScheduledAt, 'MMM') as Month, COUNT(*) as Count")
                .Where("ScheduledAt", ">=", now.AddMonths(-5).Date)
                .GroupByRaw("FORMAT(ScheduledAt, 'MMM'), MONTH(ScheduledAt)")
                .OrderByRaw("MONTH(ScheduledAt)")
                .GetAsync<MeetingActivityPointDto>();

            // Recent activity feed (last 10 events) 
            var recentMeetings = await db.Query("Meetings as m")
                .Join("AspNetUsers as u", "u.Id", "m.HostId")
                .Select("u.FullName as ActorName", "m.Title as Description", "m.ScheduledAt as OccurredAt")
                .SelectRaw("'Meeting' as Type")
                .OrderByDesc("m.ScheduledAt")
                .Limit(4)
                .GetAsync<RecentActivityDto>();

            var recentUsers = await db.Query("AspNetUsers")
                .Select("FullName as ActorName", "Email as Description", "CreatedAt as OccurredAt")
                .SelectRaw("'User' as Type")
                .OrderByDesc("CreatedAt")
                .Limit(3)
                .GetAsync<RecentActivityDto>();

            var recentFeedback = await db.Query("FeedbackReports as f")
                .Join("AspNetUsers as u", "u.Id", "f.ReporterId")
                .Select("u.FullName as ActorName", "f.Message as Description", "f.CreatedAt as OccurredAt")
                .SelectRaw("'Feedback' as Type")
                .OrderByDesc("f.CreatedAt")
                .Limit(3)
                .GetAsync<RecentActivityDto>();

            var recentActivity = recentMeetings
                .Concat(recentUsers)
                .Concat(recentFeedback)
                .OrderByDescending(x => x.OccurredAt)
                .Take(10)
                .ToList();

            return new SystemHealthDto
            {
                TotalUsers = totalUsers,
                ActiveUsers = activeUsers,
                NewUsersThisMonth = newUsersThisMonth,
                TotalMeetings = totalMeetings,
                MeetingsThisMonth = meetingsThisMonth,
                LiveMeetingsNow = liveMeetings,
                TotalTasks = totalTasks,
                PendingTasks = pendingTasks,
                CompletedTasks = completedTasks,
                TotalTranscripts = totalTranscripts,
                UnprocessedTranscripts = unprocessed,
                TotalSummaries = totalSummaries,
                EditedSummaries = editedSummaries,
                TotalNotes = totalNotes,
                AiGeneratedNotes = aiNotes,
                TotalFeedback = totalFeedback,
                OpenFeedback = openFeedback,
                InReviewFeedback = inReviewFeedback,
                BugReports = bugReports,
                UserGrowth = userGrowthRaw.ToList(),
                MeetingActivity = meetingActivityRaw.ToList(),
                RecentActivities = recentActivity
            };
        }
    }
}