using MeetIQ.Application.Common.Results;
using MeetIQ.Application.Features.Notifications.Job.DTOs;
using MeetIQ.Application.Features.Tasks.DTOs;
using MeetIQ.Application.Features.Tasks.Queries.GetTasksQuery;
using MeetIQ.Application.Interfaces.Repositories;
using MeetIQ.Domain.Entities;
using MeetIQ.Domain.Enums;
using SqlKata.Execution;

namespace MeetIQ.Infrastructure.Presistence.Repositories
{
    public class TaskRepository : Repository<TaskItem>, ITaskRepository
    {
        public TaskRepository(ApplicationDbContext context, QueryFactory db) : base(context, db)
        {
        }

        public async Task<TaskDetailsDto?> GetByIdAsync(Guid id)
        {
            var result = await db.Query("TaskItems as t")
                .Select(
                    "t.Id",
                    "t.Title",
                    "t.Description",
                    "t.Priority",
                    "t.Status",
                    "t.DueDate",
                    "t.IsAutoGenerated",
                    "t.UserId",
                    "t.MeetingId"
                )
                .Where("t.Id", id)
                .Where("t.IsDeleted", false)
                .FirstOrDefaultAsync<TaskDetailsDto>();

            return result;
        }

        public async Task<PagedResult<TaskListItemDto>> GetTasksAsync(GetTasksQuery query)
        {
            var baseQuery = db.Query("TaskItems")
                .Where("UserId", query.UserId)
                .Where("IsDeleted", false);

            // Filtering
            if (query.Status.HasValue)
                baseQuery.Where("Status", (int)query.Status);

            if (query.Priority.HasValue)
                baseQuery.Where("Priority", (int)query.Priority);

            if (!string.IsNullOrEmpty(query.Search))
                baseQuery.WhereLike("Title", $"%{query.Search}%");

            // Count
            var countQuery = baseQuery.Clone();
            var total = await countQuery.CountAsync<int>();

            // Pagination + Sorting
            var items = await baseQuery
                .OrderByDesc("CreatedAt")
                .ForPage(query.Page, query.PageSize)
                .Select("Id", "Title", "Status", "Priority", "DueDate", "IsAutoGenerated")
                .GetAsync<TaskListItemDto>();

            return new PagedResult<TaskListItemDto>
            {
                Items = items.ToList(),
                TotalCount = total,
                Page = query.Page,
                PageSize = query.PageSize
            };
        }


        public async Task<int> GetPendingTasksCount(string userId)
        {
            return await db.Query("TaskItems")
                .Where("UserId", userId)
                .Where("Status", (int)Domain.Enums.TaskStatus.ToDo)
                .Where("IsDeleted", false)
                .CountAsync<int>();
        }



        public async Task<List<TaskDueDto>> GetTasksDueBetweenAsync(DateTime from, DateTime to)
        {
            return (await db.Query("TaskItems")
                .WhereBetween("DueDate", from, to)
                .WhereNotIn("Status", new[]
                {
                    (int)Domain.Enums.TaskStatus.Done,
                    //(int)Domain.Enums.TaskStatus.Cancelled
                })
                .Where("IsDeleted", false)
                .Select("Id", "Title", "UserId", "DueDate")
                .GetAsync<TaskDueDto>()).ToList();
        }

        public async Task<List<TaskDueDto>> GetOverdueTasksAsync()
        {
            return (await db.Query("TaskItems")
                .Where("DueDate", "<", DateTime.UtcNow)
                .WhereNotIn("Status", new[]
                {
            (int)Domain.Enums.TaskStatus.Done,
            //(int)Domain.Enums.TaskStatus.Cancelled
                })
                .Where("IsDeleted", false)
                .Select("Id", "Title", "UserId", "DueDate")
                .GetAsync<TaskDueDto>()).ToList();
        }

        public async Task<bool> WasNotifiedRecentlyAsync(
            Guid taskId, NotificationType type, int withinHours)
        {
            var since = DateTime.UtcNow.AddHours(-withinHours);

            var count = await db.Query("Notifications")
                .Where("ReferenceId", taskId)
                .Where("Type", (int)type)
                .Where("CreatedAt", ">", since)
                .Where("IsDeleted", false)
                .CountAsync<int>();

            return count > 0;
        }
    }
}
