using MeetIQ.Application.Common.Results;
using MeetIQ.Application.Features.Notifications.Job.DTOs;
using MeetIQ.Application.Features.Tasks.DTOs;
using MeetIQ.Application.Features.Tasks.Queries.GetTasksQuery;
using MeetIQ.Application.Interfaces.Repositories;
using MeetIQ.Domain.Entities;
using MeetIQ.Domain.Enums;
using SqlKata.Execution;

namespace MeetIQ.Infrastructure.Presistence.Repositories
{
    public class TaskRepository : Repository<TaskItem>, ITaskRepository
    {
        public TaskRepository(ApplicationDbContext context, QueryFactory db) : base(context, db)
        {
        }

        public async Task<TaskDetailsDto?> GetByIdAsync(Guid id)
        {
            var result = await db.Query("TaskItems as t")
                .LeftJoin("AspNetUsers as a", "a.Id", "t.AssigneeId")   
                .LeftJoin("Meetings as m", "m.Id", "t.MeetingId")       
                .Select(
                    "t.Id", "t.Title", "t.Description", "t.Priority",
                    "t.Status", "t.DueDate", "t.IsAutoGenerated",
                    "t.UserId", "t.MeetingId",
                    "t.AssigneeId",
                    "a.Email as AssigneeEmail",       
                    "a.FullName as AssigneeName",     
                    "m.Title as MeetingTitle"         
                )
                .Where("t.Id", id)
                .Where("t.IsDeleted", false)
                .FirstOrDefaultAsync<TaskDetailsDto>();

            return result;
        }
        public async Task<PagedResult<TaskListItemDto>> GetTasksAsync(GetTasksQuery query)
        {
            // Tasks owned by user OR assigned to user
            var baseQuery = db.Query("TaskItems")
                .Where("IsDeleted", false)
                .Where(q => q
                    .Where("UserId", query.UserId)
                    .OrWhere("AssigneeId", query.UserId)
                );

            // Filtering
            if (query.Status.HasValue)
                baseQuery.Where("Status", (int)query.Status);

            if (query.Priority.HasValue)
                baseQuery.Where("Priority", (int)query.Priority);

            if (!string.IsNullOrEmpty(query.Search))
                baseQuery.WhereLike("Title", $"%{query.Search}%");

            // Count
            var countQuery = baseQuery.Clone();
            var total = await countQuery.CountAsync<int>();

            // Pagination + Sorting
            var items = await baseQuery
                .OrderByDesc("CreatedAt")
                .ForPage(query.Page, query.PageSize)
                .Select("Id", "Title", "Status", "Priority", "DueDate", "IsAutoGenerated", "UserId", "AssigneeId")
                .GetAsync<TaskListItemDto>();

            return new PagedResult<TaskListItemDto>
            {
                Items = items.ToList(),
                TotalCount = total,
                Page = query.Page,
                PageSize = query.PageSize
            };
        }


        public async Task<int> GetPendingTasksCount(string userId)
        {
            return await db.Query("TaskItems")
                .Where("IsDeleted", false)
                .Where(q => q
                    .Where("UserId", userId)
                    .OrWhere("AssigneeId", userId)
                )
                .Where("Status", (int)Domain.Enums.TaskStatus.ToDo)
                .CountAsync<int>();
        }



        public async Task<List<TaskDueDto>> GetTasksDueBetweenAsync(DateTime from, DateTime to)
        {
            return (await db.Query("TaskItems")
                .WhereBetween("DueDate", from, to)
                .WhereNotIn("Status", new[]
                {
                    (int)Domain.Enums.TaskStatus.Done,
                })
                .Where("IsDeleted", false)
                .Select("Id", "Title", "UserId", "DueDate")
                .GetAsync<TaskDueDto>()).ToList();
        }

        public async Task<List<TaskDueDto>> GetOverdueTasksAsync()
        {
            return (await db.Query("TaskItems")
                .Where("DueDate", "<", DateTime.UtcNow)
                .WhereNotIn("Status", new[]
                {
                    (int)Domain.Enums.TaskStatus.Done,
                })
                .Where("IsDeleted", false)
                .Select("Id", "Title", "UserId", "DueDate")
                .GetAsync<TaskDueDto>()).ToList();
        }

        public async Task<bool> WasNotifiedRecentlyAsync(
            Guid taskId, NotificationType type, int withinHours)
        {
            var since = DateTime.UtcNow.AddHours(-withinHours);

            var count = await db.Query("Notifications")
                .Where("ReferenceId", taskId)
                .Where("Type", (int)type)
                .Where("CreatedAt", ">", since)
                .Where("IsDeleted", false)
                .CountAsync<int>();

            return count > 0;
        }
    }
}