using MediatR;
using MeetIQ.Application.Interfaces.Repositories;
using MeetIQ.Domain.Entities;
using MeetIQ.Domain.Enums;
using Microsoft.Extensions.Logging;
using System.Text.Json;

namespace MeetIQ.Application.Features.Meetings.Commands.ConfirmAnalysisCommand
{
    public class ConfirmAnalysisCommandHandler
        : IRequestHandler<ConfirmAnalysisCommand, ConfirmAnalysisResult>
    {
        private readonly ISummaryRepository _summaryRepository;
        private readonly IMeetingRepository _meetingRepository;
        private readonly ITaskRepository _taskRepository;
        private readonly INoteRepository _noteRepository;
        private readonly ILogger<ConfirmAnalysisCommandHandler> _logger;

        public ConfirmAnalysisCommandHandler(
            ISummaryRepository summaryRepository,
            IMeetingRepository meetingRepository,
            ITaskRepository taskRepository,
            INoteRepository noteRepository,
            ILogger<ConfirmAnalysisCommandHandler> logger)
        {
            _summaryRepository = summaryRepository;
            _meetingRepository = meetingRepository;
            _taskRepository = taskRepository;
            _noteRepository = noteRepository;
            _logger = logger;
        }

        public async Task<ConfirmAnalysisResult> Handle(
            ConfirmAnalysisCommand request, CancellationToken ct)
        {
            var meeting = await _meetingRepository
                .GetMeetingWithTranscription(request.MeetingId, ct);

            if (meeting is null)
                return new(false, "Meeting not found.");

            if (meeting.HostId != request.RequestedByUserId)
                return new(false, "Only the host can confirm analysis.");

            try
            {
                var keyDecisionsJson = request.KeyDecisions.Any()
                    ? JsonSerializer.Serialize(request.KeyDecisions)
                    : null;

                var existing = await _summaryRepository
                    .GetAsync(s => s.MeetingId == meeting.Id);

                if (existing is null)
                {
                    await _summaryRepository.AddAsync(new MeetingSummary
                    {
                        MeetingId = meeting.Id,
                        SummaryText = request.Summary,
                        KeyInsights = request.KeyInsights,
                        KeyDecisions = keyDecisionsJson,
                        GeneratedAt = DateTime.UtcNow,
                    });
                }
                else
                {
                    existing.SummaryText = request.Summary;
                    existing.KeyInsights = request.KeyInsights;
                    existing.KeyDecisions = keyDecisionsJson;
                    existing.UpdatedAt = DateTime.UtcNow;
                    existing.IsEdited = false;
                }

                foreach (var t in request.ApprovedTasks)
                {
                    var priority = t.Priority?.ToLower() switch
                    {
                        "high" => TaskPriority.High,
                        "medium" => TaskPriority.Medium,
                        _ => TaskPriority.Low
                    };

                    DateTime? dueDate = null;
                    if (t.DueDate is not null &&
                        DateTime.TryParse(t.DueDate, out var parsed))
                        dueDate = DateTime.SpecifyKind(parsed, DateTimeKind.Utc);

                    await _taskRepository.AddAsync(new TaskItem
                    {
                        Title = t.Title,
                        Description = t.Description,
                        Priority = priority,
                        DueDate = dueDate,
                        MeetingId = meeting.Id,
                        UserId = request.RequestedByUserId,
                        IsAutoGenerated = true,
                        Status = Domain.Enums.TaskStatus.ToDo,
                        CreatedAt = DateTime.UtcNow,
                    });
                }

                foreach (var n in request.ApprovedNotes)
                {
                    await _noteRepository.AddAsync(new Note
                    {
                        Title = n.Title,
                        Content = n.Content,
                        MeetingId = meeting.Id,
                        AuthorId = request.RequestedByUserId,
                        IsAutoGenerated = true,
                        CreatedAt = DateTime.UtcNow,
                    });
                }

                await _taskRepository.SaveChangesAsync();

                _logger.LogInformation(
                    "Confirmed analysis for meeting {Id}: {T} tasks, {N} notes",
                    meeting.Id, request.ApprovedTasks.Count, request.ApprovedNotes.Count);

                return new(true, null);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Confirm analysis failed for meeting {Id}", meeting.Id);
                return new(false, ex.Message);
            }
        }
    }
}