namespace MeetIQ.Domain.Enums
{
    public enum NotificationType
    {
        // Meeting
        MeetingScheduled = 1,
        MeetingStartingSoon = 2,
        MeetingCancelled = 3,
        MeetingUpdated = 4,
        MeetingEnded = 5,

        // Participants
        ParticipantJoined = 10,
        YouWereAddedToMeeting = 11,

        // AI Features
        TranscriptReady = 20,
        SummaryReady = 21,
        TasksAutoGenerated = 22,

        // Tasks
        TaskAssigned = 30,
        TaskDueSoon = 31,
        TaskOverdue = 32,
        TaskStatusChanged = 33,

        // Notes
        NoteShared = 40,

        // Admin
        FeedbackReceived = 50,
        SystemAlert = 51,
    }
}