namespace MeetIQ.Application.Features.Dashboard.DTOs
{
    public class RecentNoteDto
    {
        public Guid Id { get; set; }
        public string Title { get; set; } = string.Empty;
        public string? Content { get; set; }
        public bool IsAutoGenerated { get; set; }
        public string? MeetingTitle { get; set; }
        public DateTime? CreatedAt { get; set; }
    }
}
