namespace MeetIQ.Application.Features.Dashboard.DTOs
{
    public class RecentTaskDto
    {
        public Guid Id { get; set; }
        public string Title { get; set; } = string.Empty;
        public int Priority { get; set; }
        public int Status { get; set; }
        public DateTime? DueDate { get; set; }
        public bool IsAutoGenerated { get; set; }
        public string? MeetingTitle { get; set; }
    }
}
