
namespace MeetIQ.Application.Features.Notes.DTOs
{
    public class NoteDetailsDto
    {
        public Guid Id { get; set; }
        public string Title { get; set; } = string.Empty;
        public string Content { get; set; } = string.Empty;
        public bool IsAutoGenerated { get; set; }
        public bool IsEdited { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
        public string AuthorId { get; set; } = string.Empty;
        public string AuthorName { get; set; } = string.Empty;
        public Guid? MeetingId { get; set; }
        public string? MeetingTitle { get; set; }
        public Guid? CalendarEventId { get; set; }
        public string? CalendarEventTitle { get; set; }

        public List<TagDto> Tags { get; set; } = [];
    }
}
