namespace MeetIQ.Application.Features.Notes.DTOs
{
    public class NoteListItemDto
    {
        public Guid Id { get; set; }
        public string Title { get; set; }
        public string ContentPreview { get; set; } 
        public bool IsAutoGenerated { get; set; }
        public bool IsEdited { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
        public string? MeetingTitle { get; set; }
        public List<string> Tags { get; set; } = new();
    }
}