//using System.ComponentModel.DataAnnotations;

//namespace MeetIQ.Interface.ViewModels
//{
//    // ─── List / Index ────────────────────────────────────────────────────────
//    public class NotesIndexViewModel
//    {
//        public IEnumerable<NoteCardViewModel> Notes { get; set; } = [];
//        public string? SearchQuery { get; set; }
//        public string? SelectedTag { get; set; }
//        public string? FilterType { get; set; }          // "all" | "manual" | "ai"
//        public IEnumerable<string> AllTags { get; set; } = [];
//        public int TotalCount { get; set; }
//    }

//    public class NoteCardViewModel
//    {
//        public Guid Id { get; set; }
//        public string Title { get; set; } = string.Empty;
//        public string ContentSnippet { get; set; } = string.Empty;   // plain-text truncated
//        public bool IsAutoGenerated { get; set; }
//        public bool IsEdited { get; set; }
//        public DateTime CreatedAt { get; set; }
//        public DateTime UpdatedAt { get; set; }
//        public string AuthorName { get; set; } = string.Empty;
//        public string? MeetingTitle { get; set; }
//        public string? CalendarEventTitle { get; set; }
//        public IEnumerable<string> Tags { get; set; } = [];
//    }

//    // ─── Detail ──────────────────────────────────────────────────────────────
//    public class NoteDetailViewModel
//    {
//        public Guid Id { get; set; }
//        public string Title { get; set; } = string.Empty;
//        public string Content { get; set; } = string.Empty;
//        public bool IsAutoGenerated { get; set; }
//        public bool IsEdited { get; set; }
//        public DateTime CreatedAt { get; set; }
//        public DateTime UpdatedAt { get; set; }
//        public string AuthorId { get; set; } = string.Empty;
//        public string AuthorName { get; set; } = string.Empty;
//        public Guid? MeetingId { get; set; }
//        public string? MeetingTitle { get; set; }
//        public Guid? CalendarEventId { get; set; }
//        public string? CalendarEventTitle { get; set; }
//        public IEnumerable<string> Tags { get; set; } = [];
//    }

//    // ─── Create ──────────────────────────────────────────────────────────────
//    public class NoteCreateViewModel
//    {
//        [Required, MaxLength(250)]
//        public string Title { get; set; } = string.Empty;

//        public string Content { get; set; } = string.Empty;

//        public Guid? MeetingId { get; set; }
//        public Guid? CalendarEventId { get; set; }

//        // Comma-separated tag names entered by the user
//        public string TagsInput { get; set; } = string.Empty;

//        // Dropdowns populated by controller
//        public IEnumerable<SelectOption> Meetings { get; set; } = [];
//        public IEnumerable<SelectOption> CalendarEvents { get; set; } = [];
//        public IEnumerable<string> AllTags { get; set; } = [];
//    }

//    // ─── Edit ────────────────────────────────────────────────────────────────
//    public class NoteEditViewModel
//    {
//        public Guid Id { get; set; }

//        [Required, MaxLength(250)]
//        public string Title { get; set; } = string.Empty;

//        public string Content { get; set; } = string.Empty;

//        public Guid? MeetingId { get; set; }
//        public Guid? CalendarEventId { get; set; }

//        public string TagsInput { get; set; } = string.Empty;

//        public bool IsAutoGenerated { get; set; }

//        public IEnumerable<SelectOption> Meetings { get; set; } = [];
//        public IEnumerable<SelectOption> CalendarEvents { get; set; } = [];
//        public IEnumerable<string> AllTags { get; set; } = [];
//    }

//    // ─── Helpers ─────────────────────────────────────────────────────────────
//    public record SelectOption(string Value, string Text);
//}