using MeetIQ.Domain.Enums;

namespace MeetIQ.Domain.Entities
{
    public class TaskItem
    {
        public Guid Id { get; set; } = Guid.NewGuid();
        public string Title { get; set; } = string.Empty;
        public string? Description { get; set; }
        public TaskPriority Priority { get; set; } = TaskPriority.Medium;
        public Enums.TaskStatus Status { get; set; } = Enums.TaskStatus.ToDo;
        public DateTime? DueDate { get; set; }
        public bool IsAutoGenerated { get; set; } = false;
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        public bool IsDeleted { get; set; } = false;
        public DateTime? DeletedAt { get; set; }

        public string UserId { get; set; }
        public ApplicationUser? User { get; set; }

        public string? AssigneeId { get; set; }
        public ApplicationUser? Assignee { get; set; }


        // Optional link to source meeting
        public Guid? MeetingId { get; set; }
        public Meeting? Meeting { get; set; }
    }

   
}
