namespace MeetIQ.Interface.ViewModels.Notes
{
    public class NoteCardViewModel
    {
        public Guid Id { get; set; }
        public string Title { get; set; } = string.Empty;

        public string ContentSnippet { get; set; } = string.Empty;
        public bool IsAutoGenerated { get; set; }
        public bool IsEdited { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
        public string AuthorName { get; set; } = string.Empty;
        public string? MeetingTitle { get; set; }
        public string? CalendarEventTitle { get; set; }
        public IEnumerable<string> Tags { get; set; } = [];
    }
}