using System.Security.Claims;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MeetIQ.Application.Features.Meetings.Queries.GetUserMeetingsQuery;
using SelectOption = MeetIQ.Web.ViewModels.Notes.SelectOption;
using NoteCreateViewModel = MeetIQ.Web.ViewModels.Notes.NoteCreateViewModel;
using NoteEditViewModel = MeetIQ.Web.ViewModels.Notes.NoteEditViewModel;
using NotesIndexViewModel = MeetIQ.Web.ViewModels.Notes.NotesIndexViewModel;
using NoteDetailViewModel = MeetIQ.Web.ViewModels.Notes.NoteDetailViewModel;
using NoteCardViewModel = MeetIQ.Web.ViewModels.Notes.NoteCardViewModel;
using MeetIQ.Application.Features.Notes.Queries.GetNotesQuery;
using MeetIQ.Application.Features.Notes.Queries.GetNoteDetailsQuery;
using MeetIQ.Application.Features.Notes.Commands.CreateNoteCommand;
using MeetIQ.Application.Features.Notes.Commands.UpdateNoteCommand;
using MeetIQ.Application.Features.Notes.Commands.DeleteNoteCommand;
using MeetIQ.Application.Features.Calendar.Queries.GetUserCalendarEvents;
using MeetIQ.Application.Features.Notes.Queries.GetAllTagsQuery;

namespace MeetIQ.Web.Controllers
{
    [Authorize]
    public class NotesController : Controller
    {
        private readonly IMediator _mediator;

        public NotesController(IMediator mediator) => _mediator = mediator;

        private string UserId =>
            User.FindFirst(ClaimTypes.NameIdentifier)?.Value
            ?? throw new UnauthorizedAccessException();

        [HttpGet]
        public async Task<IActionResult> Index(
             string? q,
             string? tag,
             string? filter,
             int page = 1)
        {
            var result = await _mediator.Send(new GetNotesQuery
            {
                UserId = UserId,
                Search = q,
                Tag = tag,
                Filter = filter,
                Page = page,
                PageSize = 12
            });

            var vm = new NotesIndexViewModel
            {
                Notes = result.Notes.Select(n => new NoteCardViewModel
                {
                    Id = n.Id,
                    Title = n.Title,
                    ContentSnippet = n.ContentSnippet,
                    IsAutoGenerated = n.IsAutoGenerated,
                    IsEdited = n.IsEdited,
                    CreatedAt = n.CreatedAt,
                    UpdatedAt = n.UpdatedAt,
                    AuthorName = n.AuthorName,
                    MeetingTitle = n.MeetingTitle,
                    CalendarEventTitle = n.CalendarEventTitle,
                    Tags = n.Tags
                }),
                SearchQuery = q,
                SelectedTag = tag,
                FilterType = filter ?? "all",
                AllTags = result.AllTags,
                TotalCount = result.Total,
                CurrentPage = page           
            };

            ViewData["Title"] = "Notes";

            // AJAX request → return partial only
            if (Request.Headers["X-Requested-With"] == "XMLHttpRequest")
                return PartialView("_NotesGrid", vm);

            return View(vm);
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var note = await _mediator.Send(new GetNoteDetailsQuery
            {
                Id = id,
                RequesterId = UserId
            });

            var vm = new NoteDetailViewModel
            {
                Id = note.Id,
                Title = note.Title,
                Content = note.Content,
                IsAutoGenerated = note.IsAutoGenerated,
                IsEdited = note.IsEdited,
                CreatedAt = note.CreatedAt,
                UpdatedAt = note.UpdatedAt,
                AuthorId = note.AuthorId,
                AuthorName = note.AuthorName,
                MeetingId = note.MeetingId,
                MeetingTitle = note.MeetingTitle,
                CalendarEventId = note.CalendarEventId,
                CalendarEventTitle = note.CalendarEventTitle,
                Tags = note.Tags.Select(t => t.Name)
            };

            ViewData["Title"] = note.Title;
            return View(vm);
        }

        [HttpGet]
        public async Task<IActionResult> Create(Guid? meetingId, Guid? calendarEventId)
        {
            var vm = await BuildCreateViewModelAsync();
            vm.MeetingId = meetingId;
            vm.CalendarEventId = calendarEventId;

            ViewData["Title"] = "New Note";
            return View(vm);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(NoteCreateViewModel model)
        {
            if (!ModelState.IsValid)
            {
                var dropdowns = await BuildCreateViewModelAsync();
                model.Meetings = dropdowns.Meetings;
                model.CalendarEvents = dropdowns.CalendarEvents;
                model.AllTags = dropdowns.AllTags;
                return View(model);
            }

            var id = await _mediator.Send(new CreateNoteCommand
            {
                Title = model.Title,
                Content = model.Content,
                AuthorId = UserId,
                MeetingId = model.MeetingId,
                CalendarEventId = model.CalendarEventId,
                Tags = ParseTags(model.TagsInput),
                IsAutoGenerated = false
            });

            TempData["Success"] = "Note created successfully.";
            return RedirectToAction(nameof(Details), new { id });
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var note = await _mediator.Send(new GetNoteDetailsQuery
            {
                Id = id,
                RequesterId = UserId
            });

            var dropdowns = await BuildEditDropdownsAsync();

            var vm = new NoteEditViewModel
            {
                Id = note.Id,
                Title = note.Title,
                Content = note.Content,
                MeetingId = note.MeetingId,
                CalendarEventId = note.CalendarEventId,
                TagsInput = string.Join(", ", note.Tags.Select(t => t.Name)),
                IsAutoGenerated = note.IsAutoGenerated,
                Meetings = dropdowns.Meetings,
                CalendarEvents = dropdowns.CalendarEvents,
                AllTags = dropdowns.AllTags
            };

            ViewData["Title"] = "Edit Note";
            return View(vm);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(NoteEditViewModel model)
        {
            if (!ModelState.IsValid)
            {
                var dropdowns = await BuildEditDropdownsAsync();
                model.Meetings = dropdowns.Meetings;
                model.CalendarEvents = dropdowns.CalendarEvents;
                model.AllTags = dropdowns.AllTags;
                return View(model);
            }

            await _mediator.Send(new UpdateNoteCommand
            {
                Id = model.Id,
                Title = model.Title,
                Content = model.Content,
                MeetingId = model.MeetingId,
                CalendarEventId = model.CalendarEventId,
                RequesterId = UserId,
                Tags = ParseTags(model.TagsInput)
            });

            TempData["Success"] = "Note updated successfully.";
            return RedirectToAction(nameof(Details), new { id = model.Id });
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Guid id)
        {
            await _mediator.Send(new DeleteNoteCommand
            {
                Id = id,
                RequesterId = UserId
            });

            TempData["Success"] = "Note deleted.";
            return RedirectToAction(nameof(Index));
        }


        // PRIVATE HELPERS 
        private async Task<NoteCreateViewModel> BuildCreateViewModelAsync()
        {
            var (meetings, events, tags) = await FetchDropdownDataAsync();
            return new NoteCreateViewModel
            {
                Meetings = meetings,
                CalendarEvents = events,
                AllTags = tags
            };
        }

        private async Task<(IEnumerable<SelectOption> Meetings,
                             IEnumerable<SelectOption> CalendarEvents,
                             IEnumerable<string> AllTags)> BuildEditDropdownsAsync()
            => await FetchDropdownDataAsync();

        // NotesController.cs - FetchDropdownDataAsync
        private async Task<(IEnumerable<SelectOption> Meetings,
                             IEnumerable<SelectOption> CalendarEvents,
                             IEnumerable<string> AllTags)> FetchDropdownDataAsync()
        {
            var meetings = (await _mediator.Send(new GetUserMeetingsQuery { UserId = UserId }))
                .Select(m => new SelectOption { Value = m.Id.ToString(), Text = m.Title });

            var events = (await _mediator.Send(new GetUserCalendarEventsQuery { UserId = UserId }))
                .Select(e => new SelectOption { Value = e.Id.ToString(), Text = e.Title });

            var tags = (await _mediator.Send(new GetAllTagsQuery()))
                .Select(t => t.Name);

            return (meetings, events, tags);
        }
        private static List<string> ParseTags(string? input)
        {
            if (string.IsNullOrWhiteSpace(input)) return [];

            return input
                .Split(',', StringSplitOptions.RemoveEmptyEntries)
                .Select(t => t.Trim().ToLower())
                .Where(t => !string.IsNullOrEmpty(t))
                .Distinct()
                .ToList();
        }
    }
}