using MediatR;
using MeetIQ.Application.Common.Exceptions;
using MeetIQ.Application.Features.Meetings.Queries.GetMeetingByIdQuery;
using MeetIQ.Application.Features.Meetings.Queries.GetUserMeetingsQuery;
using MeetIQ.Application.Features.Tasks.Commands.ChangeTaskStatusCommand;
using MeetIQ.Application.Features.Tasks.Commands.CreateTaskCommand;
using MeetIQ.Application.Features.Tasks.Commands.DeleteTaskCommand;
using MeetIQ.Application.Features.Tasks.Commands.UpdateTaskCommand;
using MeetIQ.Application.Features.Tasks.DTOs;
using MeetIQ.Application.Features.Tasks.Queries.GetTaskByIdQuery;
using MeetIQ.Application.Features.Tasks.Queries.GetTasksQuery;
using MeetIQ.Application.Features.Tasks.Services;
using MeetIQ.Domain.Enums;
using MeetIQ.Web.ViewModels.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace MeetIQ.Web.Controllers
{
    [Authorize]
    public class TasksController : Controller
    {
        private readonly IMediator mediator;

        private readonly ITaskAssignmentValidator assignmentValidator;

        public TasksController(IMediator mediator, ITaskAssignmentValidator assignmentValidator)
        {
            this.mediator = mediator;
            this.assignmentValidator = assignmentValidator;
        }

        [HttpGet]
        public async Task<IActionResult> Index(
                Domain.Enums.TaskStatus? status,
                TaskPriority? priority,
                string? search,
                int page = 1)
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            var result = await mediator.Send(new GetTasksQuery
            {
                UserId = userId,
                Status = status,
                Priority = priority,
                Search = search,
                Page = page
            });

            return View(result);
        }


        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var task = await mediator.Send(new GetTaskByIdQuery { Id = id });

            return View(task);
        }



        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var meetings = await mediator.Send(new GetUserMeetingsQuery { UserId = userId });

            return View(new CreateTaskViewModel
            {
                Meetings = meetings.Select(m => new MeetingSelectDto
                {
                    Id = m.Id,
                    Title = m.Title
                }).ToList()
            });
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateTaskViewModel model)
        {
            if (!ModelState.IsValid)
            {
                var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
                var meetings = await mediator.Send(new GetUserMeetingsQuery { UserId = userId });
                model.Meetings = meetings.Select(m => new MeetingSelectDto { Id = m.Id, Title = m.Title }).ToList();
                return View(model);
            }

            var command = new CreateTaskCommand
            {
                Title = model.Title,
                Description = model.Description,
                Priority = model.Priority,
                DueDate = model.DueDate,
                UserId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value,
                MeetingId = model.MeetingId,
                IsAutoGenerated = false,
                AssigneeEmail = model.AssigneeEmail
            };

            var id = await mediator.Send(command);
            return RedirectToAction(nameof(Details), new { id });
        }

        [HttpGet]
        public async Task<IActionResult> ValidateAssignee(string email, Guid? meetingId)
        {
            if (string.IsNullOrEmpty(email) || !meetingId.HasValue)
                return Json(new { valid = false, message = "Email and meeting are required." });

            try
            {
                var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value!;
                await assignmentValidator.ValidateAndResolveAsync(email, meetingId, userId);
                return Json(new { valid = true });
            }
            catch (BadRequestException ex)
            {
                return Json(new { valid = false, message = ex.Message });
            }
        }

        [HttpGet]
        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var task = await mediator.Send(new GetTaskByIdQuery { Id = id });
            if (task == null) return NotFound();

            var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var meetings = await mediator.Send(new GetUserMeetingsQuery { UserId = userId });

            var meetingList = meetings
                .Select(m => new MeetingSelectDto { Id = m.Id, Title = m.Title })
                .ToList();

            if (task.MeetingId.HasValue &&
                meetingList.All(m => m.Id != task.MeetingId.Value))
            {
                var linkedMeeting = await mediator.Send(
                    new GetMeetingByIdQuery { MeetingId = task.MeetingId.Value });

                if (linkedMeeting != null)
                    meetingList.Insert(0, new MeetingSelectDto
                    {
                        Id = linkedMeeting.Id,
                        Title = linkedMeeting.Title
                    });
            }

            var vm = new UpdateTaskViewModel
            {
                Id = task.Id,
                Title = task.Title,
                Description = task.Description,
                Priority = Enum.TryParse<TaskPriority>(task.Priority, out var p)
                                    ? p : TaskPriority.Medium,
                Status = Enum.TryParse<Domain.Enums.TaskStatus>(task.Status, out var s)
                                    ? s : Domain.Enums.TaskStatus.ToDo,
                DueDate = task.DueDate,
                MeetingId = task.MeetingId,
                AssigneeEmail = task.AssigneeEmail,   
                Meetings = meetingList
            };

            return View(vm);
        }
        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(UpdateTaskViewModel model)
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value!;

                await mediator.Send(new UpdateTaskCommand
                {
                    TaskId = model.Id,           
                    RequesterId = userId,        
                    Title = model.Title,
                    Description = model.Description,
                    Priority = model.Priority,
                    Status = model.Status,       
                    DueDate = model.DueDate,
                    AssigneeEmail = model.AssigneeEmail, 
                    ClearAssignee = model.ClearAssignee  
                });

            return RedirectToAction(nameof(Details), new { id = model.Id });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ChangeStatus(Guid taskId, Domain.Enums.TaskStatus status)
        {
            await mediator.Send(new ChangeTaskStatusCommand
            {
                TaskId = taskId,
                Status = status
            });

            return RedirectToAction("Details", new { id = taskId });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Guid id)
        {
            await mediator.Send(new DeleteTaskCommand
            {
                TaskId = id
            });

            return RedirectToAction("Index");
        }

    }
}
