using MeetIQ.Application.Common.Options;
using MeetIQ.Application.Interfaces.Services;
using MeetIQ.Domain.Entities;
using MeetIQ.Infrastructure.Presistence;
using Microsoft.EntityFrameworkCore;
using System.Text.RegularExpressions;

namespace MeetIQ.Infrastructure.Services
{
    public class NoteService : INoteService
    {
        private readonly ApplicationDbContext _db;

        public NoteService(ApplicationDbContext db)
        {
            _db = db;
        }

        // ── helpers ──────────────────────────────────────────────────────────
        private static string StripHtml(string html) =>
            string.IsNullOrWhiteSpace(html)
                ? string.Empty
                : Regex.Replace(html, "<.*?>", " ").Trim();

        private static string Truncate(string s, int max) =>
            s.Length <= max ? s : s[..max].TrimEnd() + "…";

        // ── Index ─────────────────────────────────────────────────────────────
        public async Task<NotesIndexViewModel> GetIndexAsync(
            string userId, string? search, string? tag, string? filterType)
        {
            var query = _db.Notes
                .Include(n => n.Author)
                .Include(n => n.Meeting)
                .Include(n => n.CalendarEvent)
                .Include(n => n.NoteTags).ThenInclude(nt => nt.Tag)
                .Where(n => n.AuthorId == userId)
                .AsNoTracking();

            if (!string.IsNullOrWhiteSpace(search))
                query = query.Where(n =>
                    n.Title.Contains(search) || n.Content.Contains(search));

            if (!string.IsNullOrWhiteSpace(tag))
                query = query.Where(n =>
                    n.NoteTags.Any(nt => nt.Tag.Name == tag));

            if (filterType == "ai")
                query = query.Where(n => n.IsAutoGenerated);
            else if (filterType == "manual")
                query = query.Where(n => !n.IsAutoGenerated);

            var notes = await query
                .OrderByDescending(n => n.UpdatedAt)
                .ToListAsync();

            var allTags = await _db.NoteTags
                .Include(nt => nt.Tag)
                .Where(nt => nt.Note.AuthorId == userId)
                .Select(nt => nt.Tag.Name)
                .Distinct()
                .OrderBy(t => t)
                .ToListAsync();

            return new NotesIndexViewModel
            {
                Notes = notes.Select(n => new NoteCardViewModel
                {
                    Id = n.Id,
                    Title = n.Title,
                    ContentSnippet = Truncate(StripHtml(n.Content), 140),
                    IsAutoGenerated = n.IsAutoGenerated,
                    IsEdited = n.IsEdited,
                    CreatedAt = n.CreatedAt,
                    UpdatedAt = n.UpdatedAt,
                    AuthorName = n.Author.FullName,
                    MeetingTitle = n.Meeting?.Title,
                    CalendarEventTitle = n.CalendarEvent?.Title,
                    Tags = n.NoteTags.Select(nt => nt.Tag.Name)
                }),
                SearchQuery = search,
                SelectedTag = tag,
                FilterType = filterType ?? "all",
                AllTags = allTags,
                TotalCount = notes.Count
            };
        }

        // ── Detail ────────────────────────────────────────────────────────────
        public async Task<NoteDetailViewModel?> GetDetailAsync(Guid id, string userId)
        {
            var n = await _db.Notes
                .Include(n => n.Author)
                .Include(n => n.Meeting)
                .Include(n => n.CalendarEvent)
                .Include(n => n.NoteTags).ThenInclude(nt => nt.Tag)
                .AsNoTracking()
                .FirstOrDefaultAsync(n => n.Id == id && n.AuthorId == userId);

            if (n is null) return null;

            return new NoteDetailViewModel
            {
                Id = n.Id,
                Title = n.Title,
                Content = n.Content,
                IsAutoGenerated = n.IsAutoGenerated,
                IsEdited = n.IsEdited,
                CreatedAt = n.CreatedAt,
                UpdatedAt = n.UpdatedAt,
                AuthorId = n.AuthorId,
                AuthorName = n.Author.FullName,
                MeetingId = n.MeetingId,
                MeetingTitle = n.Meeting?.Title,
                CalendarEventId = n.CalendarEventId,
                CalendarEventTitle = n.CalendarEvent?.Title,
                Tags = n.NoteTags.Select(nt => nt.Tag.Name)
            };
        }

        // ── Create form ───────────────────────────────────────────────────────
        public async Task<NoteCreateViewModel> GetCreateFormAsync(
            Guid? meetingId, Guid? calendarEventId)
        {
            return new NoteCreateViewModel
            {
                MeetingId = meetingId,
                CalendarEventId = calendarEventId,
                Meetings = await MeetingOptionsAsync(),
                CalendarEvents = await CalendarEventOptionsAsync(),
                AllTags = await AllTagNamesAsync()
            };
        }

        // ── Create ────────────────────────────────────────────────────────────
        public async Task<Guid> CreateAsync(NoteCreateViewModel vm, string userId)
        {
            var note = new Note
            {
                Title = vm.Title.Trim(),
                Content = vm.Content,
                AuthorId = userId,
                MeetingId = vm.MeetingId,
                CalendarEventId = vm.CalendarEventId,
                IsAutoGenerated = false
            };

            _db.Notes.Add(note);
            await _db.SaveChangesAsync();

            await SyncTagsAsync(note.Id, vm.TagsInput);
            return note.Id;
        }

        // ── Edit form ─────────────────────────────────────────────────────────
        public async Task<NoteEditViewModel?> GetEditFormAsync(Guid id, string userId)
        {
            var n = await _db.Notes
                .Include(n => n.NoteTags).ThenInclude(nt => nt.Tag)
                .FirstOrDefaultAsync(n => n.Id == id && n.AuthorId == userId);

            if (n is null) return null;

            return new NoteEditViewModel
            {
                Id = n.Id,
                Title = n.Title,
                Content = n.Content,
                MeetingId = n.MeetingId,
                CalendarEventId = n.CalendarEventId,
                TagsInput = string.Join(", ", n.NoteTags.Select(nt => nt.Tag.Name)),
                IsAutoGenerated = n.IsAutoGenerated,
                Meetings = await MeetingOptionsAsync(),
                CalendarEvents = await CalendarEventOptionsAsync(),
                AllTags = await AllTagNamesAsync()
            };
        }

        // ── Update ────────────────────────────────────────────────────────────
        public async Task<bool> UpdateAsync(NoteEditViewModel vm, string userId)
        {
            var note = await _db.Notes
                .Include(n => n.NoteTags)
                .FirstOrDefaultAsync(n => n.Id == vm.Id && n.AuthorId == userId);

            if (note is null) return false;

            note.Title = vm.Title.Trim();
            note.Content = vm.Content;
            note.MeetingId = vm.MeetingId;
            note.CalendarEventId = vm.CalendarEventId;
            note.UpdatedAt = DateTime.UtcNow;
            note.IsEdited = true;

            _db.NoteTags.RemoveRange(note.NoteTags);
            await _db.SaveChangesAsync();

            await SyncTagsAsync(note.Id, vm.TagsInput);
            return true;
        }

        // ── Delete ────────────────────────────────────────────────────────────
        public async Task<bool> DeleteAsync(Guid id, string userId)
        {
            var note = await _db.Notes
                .FirstOrDefaultAsync(n => n.Id == id && n.AuthorId == userId);

            if (note is null) return false;

            _db.Notes.Remove(note);
            await _db.SaveChangesAsync();
            return true;
        }

        // ── Private helpers ───────────────────────────────────────────────────
        private async Task SyncTagsAsync(Guid noteId, string tagsInput)
        {
            if (string.IsNullOrWhiteSpace(tagsInput)) return;

            var names = tagsInput
                .Split(',', StringSplitOptions.RemoveEmptyEntries)
                .Select(t => t.Trim())
                .Where(t => t.Length > 0)
                .Distinct(StringComparer.OrdinalIgnoreCase);

            foreach (var name in names)
            {
                var tag = await _db.Tags.FirstOrDefaultAsync(t => t.Name == name)
                          ?? new Tag { Name = name };

                if (tag.Id == 0)
                {
                    _db.Tags.Add(tag);
                    await _db.SaveChangesAsync();
                }

                _db.NoteTags.Add(new NoteTag { NoteId = noteId, TagId = tag.Id });
            }

            await _db.SaveChangesAsync();
        }

        private async Task<IEnumerable<SelectOption>> MeetingOptionsAsync() =>
            await _db.Meetings
                .OrderByDescending(m => m.ScheduledAt)
                .Select(m => new SelectOption(m.Id.ToString(), m.Title))
                .ToListAsync();

        private async Task<IEnumerable<SelectOption>> CalendarEventOptionsAsync() =>
            await _db.CalendarEvents
                .OrderByDescending(c => c.StartTime)
                .Select(c => new SelectOption(c.Id.ToString(), c.Title))
                .ToListAsync();

        private async Task<IEnumerable<string>> AllTagNamesAsync() =>
            await _db.Tags.Select(t => t.Name).OrderBy(t => t).ToListAsync();
    }
}
