namespace MeetIQ.Application.Features.Tasks.DTOs
{
    public class TaskDetailsDto
    {
        public Guid Id { get; set; }
        public string Title { get; set; }
        public string? Description { get; set; }

        public string? AssigneeId { get; set; }
        public string? AssigneeName { get; set; }
        public string? AssigneeEmail { get; set; }

        public string Priority { get; set; }
        public string Status { get; set; }

        public DateTime? DueDate { get; set; }

        public bool IsAutoGenerated { get; set; }

        public Guid? MeetingId { get; set; }
    }
}
