namespace MeetIQ.Application.Features.Tasks.DTOs
{
    public class TaskDetailsDto
    {
        public Guid Id { get; set; }
        public string Title { get; set; } = string.Empty;
        public string? Description { get; set; }
        public string Priority { get; set; } = string.Empty;
        public string Status { get; set; } = string.Empty;
        public DateTime? DueDate { get; set; }
        public bool IsAutoGenerated { get; set; }
        public string UserId { get; set; } = string.Empty;
        public Guid? MeetingId { get; set; }
        public string? MeetingTitle { get; set; }    
        public string? AssigneeId { get; set; }
        public string? AssigneeEmail { get; set; }
        public string? AssigneeName { get; set; }   
    }
}