using MeetIQ.Domain.Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MeetIQ.Application.Features.Tasks.DTOs
{
    public class TaskListItemDto
    {
        public Guid Id { get; set; }
        public string Title { get; set; }

        public Domain.Enums.TaskStatus Status { get; set; }
        public TaskPriority Priority { get; set; }

        public DateTime? DueDate { get; set; }

        public bool IsAutoGenerated { get; set; }
    }
}
