using MeetIQ.Domain.Enums;

namespace MeetIQ.Application.Features.Tasks.DTOs
{
    public class TaskListItemDto
    {
        public Guid Id { get; set; }
        public string Title { get; set; }
        public string? AssigneeName { get; set; }

        public Domain.Enums.TaskStatus Status { get; set; }
        public TaskPriority Priority { get; set; }

        public DateTime? DueDate { get; set; }

        public bool IsAutoGenerated { get; set; }
    }
}
