using MediatR;
using MeetIQ.Application.Interfaces.Repositories;
using MeetIQ.Application.Interfaces;
using MeetIQ.Domain.Entities;
using MeetIQ.Application.Common.Exceptions;

namespace MeetIQ.Application.Features.Tasks.Commands.CreateTaskCommand
{
    public class CreateTaskCommandHandler : IRequestHandler<CreateTaskCommand, Guid>
    {
        private readonly ITaskRepository taskRepository;
        private readonly IMeetingRepository meetingRepository;
        private readonly IUserRepository userRepository;

        public CreateTaskCommandHandler(
           ITaskRepository taskRepository,
           IMeetingRepository meetingRepository,
           IUserRepository userRepository)
        {
            this.taskRepository = taskRepository;
            this.meetingRepository = meetingRepository;
            this.userRepository = userRepository;
        }

        public async Task<Guid> Handle(CreateTaskCommand request, CancellationToken cancellationToken)
        {
            // Meeting validation
            if (request.MeetingId.HasValue)
            {
                var meeting = await meetingRepository.GetAsync(x => x.Id == request.MeetingId);

                if (meeting == null)
                    throw new NotFoundException("Meeting not found");
            }

            // AI tasks rule
            if (request.IsAutoGenerated && string.IsNullOrWhiteSpace(request.Title))
            {
                throw new BadRequestException("AI generated tasks must have a title");
            }


            var task = new TaskItem
            {
                Id = Guid.NewGuid(),
                Title = request.Title,
                Description = request.Description,
                Priority = request.Priority,
                DueDate = request.DueDate,
                UserId = request.UserId,
                MeetingId = request.MeetingId,
                IsAutoGenerated = request.IsAutoGenerated,
                Status = Domain.Enums.TaskStatus.ToDo,
                CreatedAt = DateTime.UtcNow
            };

            await taskRepository.AddAsync(task);
            await taskRepository.SaveChangesAsync();

            return task.Id;
        }
    }
}
