using MeetIQ.Application.Interfaces;
using MeetIQ.Domain.Enums;

namespace MeetIQ.Application.Features.Tasks.Commands.CreateTaskCommand
{
    public class CreateTaskCommand : ICommand<Guid>
    {
        public string Title { get; set; }
        public string? Description { get; set; }

        public TaskPriority Priority { get; set; }
        public DateTime? DueDate { get; set; }

        public string UserId { get; set; }
        public Guid? MeetingId { get; set; }

        public bool IsAutoGenerated { get; set; }

        public string? AssigneeEmail { get; set; }

    }
}
