using MediatR;
using MeetIQ.Application.Common.Exceptions;
using MeetIQ.Application.Features.Tasks.Services;
using MeetIQ.Application.Interfaces.Repositories;
using MeetIQ.Domain.Entities;
using MeetIQ.Domain.Enums;

namespace MeetIQ.Application.Features.Tasks.Commands.CreateTaskCommand
{
    public class CreateTaskCommandHandler : IRequestHandler<CreateTaskCommand, Guid>
    {
        private readonly ITaskRepository taskRepository;
        private readonly IMeetingRepository meetingRepository;
        private readonly IUserRepository userRepository;
        private readonly ITaskAssignmentValidator assignmentValidator; 

        public CreateTaskCommandHandler(
            ITaskRepository taskRepository,
            IMeetingRepository meetingRepository,
            IUserRepository userRepository,
            ITaskAssignmentValidator assignmentValidator)
        {
            this.taskRepository = taskRepository;
            this.meetingRepository = meetingRepository;
            this.userRepository = userRepository;
            this.assignmentValidator = assignmentValidator;
        }

        public async Task<Guid> Handle(
            CreateTaskCommand request,
            CancellationToken cancellationToken)
        {
            // Meeting validation
            if (request.MeetingId.HasValue)
            {
                var meeting = await meetingRepository.GetAsync(x => x.Id == request.MeetingId);
                if (meeting == null)
                    throw new NotFoundException("Meeting not found");
            }

            // AI tasks rule
            if (request.IsAutoGenerated && string.IsNullOrWhiteSpace(request.Title))
                throw new BadRequestException("AI generated tasks must have a title");

            // Resolve assignee
            string? assigneeId = null;

            if (!string.IsNullOrEmpty(request.AssigneeEmail))
            {
                assigneeId = await assignmentValidator.ValidateAndResolveAsync(
                    request.AssigneeEmail,
                    request.MeetingId,
                    request.UserId);
            }

            var task = new TaskItem
            {
                Id = Guid.NewGuid(),
                Title = request.Title,
                Description = request.Description,
                Priority = request.Priority,
                DueDate = request.DueDate,
                UserId = request.UserId,
                MeetingId = request.MeetingId,
                AssigneeId = assigneeId,            
                IsAutoGenerated = request.IsAutoGenerated,
                Status = Domain.Enums.TaskStatus.ToDo,
                CreatedAt = DateTime.UtcNow
            };

            await taskRepository.AddAsync(task);
            await taskRepository.SaveChangesAsync();

            return task.Id;
        }
    }
}